#%RAML 1.0 NamedExample
productID:
                {
                  "productid": 35,
                  "catagoryid": 23,
                  "name": "HP",
                  "description": "cor I 5",
                  "video_url": "www.h.com",
                  "price": 5000
                 }      
          