#%RAML 1.0 NamedExample
product2:
  [
                 {
                  "productid": 3,
                  "catagoryid": 23,
                  "name": "HP",
                  "description": "cor I 5",
                  "video_url": "www.h.com",
                  "price": 5000
                },            
                                  {   
                  "productid": 2,
                  "catagoryid": 13,
                  "name": "Dell",
                  "description": "cor I 5",
                  "video_url": "www.dell.com",
                  "price": 1000
                  }
                  ]       
              